### ISSUE TITLE
Bug in Version: 8d6f9c6

### ISSUE THREAD

**Issue by TechnicJelle** [Moros1138/PGEtinker#122]
**Describe the bug**
The rename functionality of the code editor doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to PGEtinker, the standard demo project is fine
2. Right-click on the class name
3. Click the "Rename symbol" button
4. Type in a new name
5. Press enter
The text box popup disappears, but the symbol does not get renamed.

**Expected behaviour**
The symbol gets properly renamed

**Video**

https://github.com/user-attachments/assets/82fba0b8-4638-4533-adf3-16d753a82993

**Desktop:**
 - OS: Manjaro Linux x86_64, Kernel: 6.6.41-1-MANJARO
 - Browser: Firefox
 - Version: 128.0 (64-bit)

**Comment by Moros1138** [comment]
Good news! I found out why this was happening and found a solution. It turns out it was a problem with the language server. It had a C++ file in the project that it has been including in all of the information about state changes.. The "Rename Symbol" function tries to work on multiple files... the PGEtinker frontend only knows of 1 file.. the language server had 2 files in mind.. the problem magically went away when i removed the file from the language server's project!!

anyways, I'm trying to solve a visual problem with that input (the text is black, hard to read) ... before I push the changes to make that all work.
